version = 1

# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

[[annotations]]
path = [
	 "tests/dist/**",
	 "img/favicon/**",
	 "test_coverage_report*",
         "*.lock"
]

SPDX-License-Identifier = "Apache-2.0"
SPDX-FileCopyrightText = "2025 The Linux Foundation"
