---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

name: "OpenSSF Scorecard"
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  branch_protection_rule:
  schedule:
    - cron: "50 4 * * 0"
  push:
    branches: ["main", "master"]
    paths:
      - "**"
      - "!.github/**"

# Declare default permissions as none.
permissions: {}

jobs:
  openssf-scorecard:
    name: "OpenSSF Scorecard"
    # yamllint disable-line rule:line-length
    uses: lfit/releng-reusable-workflows/.github/workflows/reuse-openssf-scorecard.yaml@b9ad414863182bd1f633be67191e49f5e64ebec2 # v0.2.17
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      # Needed to publish results and get a badge (see publish_results below).
      id-token: write
      # Uncomment the permissions below if installing in a private repository.
      # contents: read
      # actions: read
