---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Verifies action/workflow calls are pinned to SHA commit values
name: '📌 Audit GitHub Actions'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
    paths: ['.github/**']

permissions: {}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  verify:
    name: 'Check SHA pinned actions'
    # yamllint disable-line rule:line-length
    uses: lfit/releng-reusable-workflows/.github/workflows/reuse-verify-github-actions.yaml@2e3a6189595647fd51134412de8d7d9a56f2081c  # v0.2.16
    permissions:
      contents: read
